=== ConstancaElias/DAW2020/T2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT projectRecord (metadata, workteam, abstract, deliverables)>

<!ELEMENT metadata (keyname, title, subtitle*, date, supervisor)>
<!ELEMENT workteam (element+)>
<!ELEMENT abstract (paragraph, (paragraph)+)>
<!ELEMENT deliverables (link+)>

<!ELEMENT keyname (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT date (beginDate, endDate)>

<!ELEMENT beginDate (#PCDATA)>
<!ELEMENT endDate (#PCDATA)>

<!ELEMENT supervisor (link)>

<!ELEMENT link (#PCDATA)>
<!ATTLIST link url CDATA #REQUIRED>

<!ELEMENT element (name,mail,link,number) >

<!ELEMENT name (#PCDATA) >
<!ELEMENT mail (link) >
<!ELEMENT number (#PCDATA) >

<!ELEMENT paragraph (text|bold|italic|underline|link) >
<!ELEMENT bold (#PCDATA)>
<!ELEMENT italic (#PCDATA)>
<!ELEMENT underline (#PCDATA)>

=== ConstancaElias/DAW2020/T2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "pr.dtd">
<projectRecord>
    <metadata>
        <keyname></keyname>
        <title></title>
        <date>
            <beginDate></beginDate>
            <endDate></endDate>
        </date>
        <supervisor>
            <link url=""></link>
        </supervisor>
    </metadata>
    <workteam>
        <element>
            <name></name>
            <mail>
                <link url=""></link>
            </mail>
            <link url=""></link>
            <number></number>
        </element>
    </workteam>
    <abstract>
        <paragraph></paragraph>
        <paragraph></paragraph>
    </abstract>
    <deliverables>
        <link url=""></link>
    </deliverables>
</projectRecord>
